sudo: required
services:
  - docker

before_install:
  - docker build -t akiyuki/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run akiyuki/react-test npm test -- --coverage

after_success:
  - docker build -t akiyuki/multi-client ./client
  - docker build -t akiyuki/multi-nginx ./nginx
  - docker build -t akiyuki/multi-server ./server
  - docker build -t akiyuki/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push akiyuki/multi-client
  - docker push akiyuki/multi-nginx
  - docker push akiyuki/multi-server
  - docker push akiyuki/multi-worker

deploy:
        provider: elasticbeanstalk
        region: "us-east-2"
        app: "multi-docker"
        env: "MultiDocker-env"
        bucket_name: "elasticbeanstalk-us-east-2-133825813322"
        bucket_path: "docker-multi"
        on:
                branch: master
        access_key_id: "$AWS_ACCESS_KEY"
        secret_access_key:
                secure: "$AWS_SECRET_KEY"
